src/books/urls.py
from django.urls import path
from books import views
app_name = 'books'

urlpatterns = [
    path('book_list_view/', views.BookListView.as_view(), name="book_list"),
    path('book_view/<int:pk>', views.BookView.as_view(), name="book_view"),
    path('book_delete/<int:pk>', views.BookDeleteView.as_view(), name="book_delete"),
    path('book_add/', views.BookCreateView.as_view(), name="book_add"),
    path('book_upd/<int:pk>', views.BookUpdateView.as_view(), name="book_update"),
    # COMMENTS
    path('book/<int:comment_id>/comment/', views.add_comment, name='add_comment'),
]

src/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartDetailView.as_view(), name="view-cart"),
    path('cart-items-edit/', views.CartAddDeleteItemView.as_view(), name="cart-items-edit"),
    path('create-order/', views.CreateOrder.as_view(), name="create-order"),
    path('complete-order/', views.OrderSuccess.as_view(), name="complete-order"),
    path('orders-history/', views.history_order, name="history-order"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views


urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace ='directories'), name = "directories"),
    path('staff/', include('staff.urls', namespace ='staff'), name = "staff"),
    path('orders/', include('orders.urls', namespace ='orders'), name = "orders"),
    path('books/', include('books.urls', namespace ='books'), name = "books"),
    path('search/', include('search.urls', namespace ='search'), name = "search"),
    path('', home_views.HomePage.as_view(), name="Home Page"),
  
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/search/urls.py
from django.urls import path
from . import views
app_name = 'search'

urlpatterns = [
    path('', views.search_view, name="search-view"),
]

src/staff/urls.py
from django.urls import path
from .views import ProfileUpdateView, ProfileDetailView, UserRegisterView, \
    UserLoginView, UserLogoutView, UserPasswordChangeView, UserForgotPasswordView, UserPasswordResetConfirmView,\
    UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmedView, EmailConfirmationFailedView
app_name = 'staff'


urlpatterns = [
    path('user/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('user/<str:slug>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),



]

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
  <head>
    <script src="{% static '/js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{%block TITLE %} {%endblock TITLE %}</title>

    

    

<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap_icons/font/bootstrap-icons.css' %}" rel="stylesheet">
<link href="{% static '/css/stylish-card.css' %}" rel="stylesheet">

    <!-- Favicons -->

<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href='{% static "css/sticky-footer-navbar.css" %}' rel="stylesheet">
  </head>
<body class="d-flex flex-column h-100">
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
  </svg>
  <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
      <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
      <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
          Light
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
          Dark
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
          Auto
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
    </ul>
  </div>

<header>

<!-- Fixed navbar -->

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Home Page' %}">
    <img src="{% static '/logo/book_logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
    Bookshop </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-1">
        <li class="nav-item">
          <a class="nav-link active" aria-current="/home_page" href="{% url 'Home Page' %}">Главная</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:book_list' %}">Книги</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Справочники
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'directories:authors_list' %}">Авторы</a></li>
            <li><a class="dropdown-item" href="{% url 'directories:genres_list' %}">Жанры</a></li>
            <li><a class="dropdown-item" href="{% url 'directories:publishers_list' %}">Издатели</a></li>
            <li><a class="dropdown-item" href="{% url 'directories:series_list' %}">Серии</a></li>
          </ul>
        </li>

      </ul>

  

      <ul class="navbar-nav d-flex justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'search:search-view' %}"> Поиск <i class="bi bi-search"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'orders:view-cart' %}"> Корзина <i class="bi bi-cart"></i></a>
        </li>
      </ul>

      

      <ul class="navbar-nav d-flex justify-content-end">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Привет, {{ request.user.first_name }}!
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'staff:profile_detail' user %}">Profile info</a></li>
            <li><a class="dropdown-item" href="{% url 'staff:profile_edit' %}">Edit profile</a></li>
            <li><a class="dropdown-item" href="{% url 'staff:logout' %}">Logout</a></li>
            
            
           </a>
            
            
          </ul> 
        </li>
        {% endif %}
        <li class="nav-item">
          {% if not request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'staff:login' %}">Login<i class="bi bi-box-arrow-in-right"></i></a>
          {% endif %}
        </li>
      </ul>
      

    </div>
  </div>
</nav>
</header>



<main class="flex-shrink-0">
  <div class="container">
    {% include 'includes/messages.html' %}

    {% block BODY %}{% endblock BODY %}   
  </div>
</main>

<script src="{% static "js/bootstrap.bundle.min.js" %}"></script> 

</body>
</html>