src/books/urls.py
from django.urls import path
from books import views
app_name = 'books'

urlpatterns = [
    path('book_list_view/', views.BookListView.as_view(), name="book_list"),
    path('book_view/<int:pk>', views.BookView.as_view(), name="book_view"),
    path('book_delete/<int:pk>', views.BookDeleteView.as_view(), name="book_delete"),
    path('book_add/', views.BookCreateView.as_view(), name="book_add"),
    path('book_upd/<int:pk>', views.BookUpdateView.as_view(), name="book_update"),
    # COMMENTS
    path('book/<int:comment_id>/comment/', views.add_comment, name='add_comment'),
]

src/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartDetailView.as_view(), name="view-cart"),
    path('cart-items-edit/', views.CartAddDeleteItemView.as_view(), name="cart-items-edit"),
    path('create-order/', views.CreateOrder.as_view(), name="create-order"),
    path('complete-order/', views.OrderSuccess.as_view(), name="complete-order"),
    path('orders-history/', views.history_order, name="history-order"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views


urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace ='directories'), name = "directories"),
    path('staff/', include('staff.urls', namespace ='staff'), name = "staff"),
    path('orders/', include('orders.urls', namespace ='orders'), name = "orders"),
    path('books/', include('books.urls', namespace ='books'), name = "books"),
    path('search/', include('search.urls', namespace ='search'), name = "search"),
    path('', home_views.HomePage.as_view(), name="Home Page"),
  
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from datetime import date
from django.core.validators import MaxValueValidator, MinValueValidator
from pathlib import Path
from django.utils import timezone
from PIL import Image
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Books(models.Model): 
    
    book_name = models.CharField(
        verbose_name="Book's name",
        max_length = 40,
        null = False,
        blank = False
    )
    picture = models.ImageField(
        verbose_name="Book picture",
        upload_to="uploads/%Y/%m/%d/",
        default='images/default_book.png',
        blank=True
    )
    book_price = models.DecimalField(
        verbose_name= "Book's price",
        decimal_places=2,
        max_digits=6,
        validators=[MinValueValidator(0)]
    )
    book_author = models.ForeignKey(
        "directories.Author", 
        verbose_name=("Author"), 
        blank = True,
        null = True,
        on_delete=models.CASCADE
    )
    book_serie = models.ForeignKey(
        "directories.Serie", 
        verbose_name=("Serie"), 
        blank = True,
        null = True,
        on_delete=models.CASCADE
    )
    book_genre = models.ForeignKey(
        "directories.Genre", 
        verbose_name=("Genre"), 
        blank = True,
        null = True,
        on_delete=models.CASCADE
    )
    book_year = models.PositiveIntegerField(
        verbose_name=("Year"), 
        blank = True,
        null = True,
        validators=[MaxValueValidator(2023)]
    )
    book_page = models.PositiveIntegerField(
        verbose_name=("Pages"), 
        blank = True,
        null = True
    )
    COVER_BOOK = (
        ('M', 'мягкая'),
        ('T', 'твердая'),
    )
    book_cover = models.CharField(
        verbose_name=("Cover"),
        max_length = 5,
        choices= COVER_BOOK,
        default= "M"
    )
    book_isbn = models.CharField(
        verbose_name=("ISBN"), 
        max_length = 17,
        blank = True,
        null = True
    )
    book_weight = models.PositiveIntegerField(
        verbose_name=("Weight"), 
        blank = True,
        null = True,
        validators=[MinValueValidator(1)]
    )
    book_age = models.CharField(
        verbose_name=("Age Restrictions"), 
        max_length = 3,
        blank = True,
        null = True
    )
    book_publisher = models.ForeignKey(
        "directories.Publisher", 
        verbose_name=("Publisher"), 
        blank = True,
        null = True,
        on_delete=models.CASCADE
    )
    book_quantity = models.PositiveIntegerField(
        verbose_name=("Book quantity"), 
        blank = True,
        null = True
    )
    ISACTIVE = (
        ('Y', 'активна'),
        ('N', 'не активна'),
    )
    is_active = models.CharField(
        verbose_name = 'Book active',
        max_length = 4,
        choices = ISACTIVE
    )
    
    book_rating = models.DecimalField( 
        verbose_name=("Book rating"),
        max_digits=4,
        decimal_places=2, 
        default=0,
        validators=[MaxValueValidator(10), MinValueValidator(0)]
    )
    created_at = models.DateTimeField(
        auto_now_add=True)
    
    updated_at = models.DateTimeField(
        auto_now=True
        )
    

    def __str__(self):
        return str(self.book_name)
 
    def get_absolute_url(self):
        return reverse_lazy ('directories:Success_Page')
    
    def get_search_url_books(self):
        return f"/books/book_view/{self.pk}"

    def book_picture_med (self):
        original_url = self.picture.url
        new_url = original_url.split('.')
        picture_url = ".".join(new_url[:-1]) + "_150_." + new_url[-1]
        return picture_url

    def book_picture_small (self):
        original_url = self.picture.url
        new_url = original_url.split('.')
        picture_url = ".".join(new_url[:-1]) + "_40_." + new_url[-1]
        return picture_url

    def picture_resizer (self):
        extention = self.picture.file.name.split('.')[-1]
        BASE_DIR = Path(self.picture.file.name).resolve().parent
        file_name = Path(self.picture.file.name).resolve().name.split('.')
        for m_basewidth in [150, 40]:
                im = Image.open(self.picture.file.name)
                wpercent = (m_basewidth/float(im.size[0]))
                hsize = int((float(im.size[1])*float(wpercent)))
                im.thumbnail ((m_basewidth,hsize), Image.Resampling.LANCZOS)
                im.save(str(BASE_DIR / '.'.join(file_name[:-1])) + f'_{m_basewidth}_.' + extention)
    
class Comments(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE, related_name = 'comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=150)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.book, self.user)

src/books/forms.py
from django import forms
from . import models
from django.db.migrations.state import get_related_models_tuples
from .models import Comments
from django.utils.translation import gettext_lazy as _

class BookModelForm(forms.ModelForm):
    class Meta:
        model = models.Books
        fields = (
            'book_name',
            'picture',
            'book_price',
            'book_author',
            'book_serie',
            'book_genre',
            'book_year',
            'book_page',
            'book_cover',
            'book_isbn',
            'book_weight',
            'book_age',
            'book_publisher',
            'book_quantity',
            'is_active',
            'book_rating',
                   
        )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['body']

src/books/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django import forms
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .forms import CommentForm
from .models import Books
from . import models
from . import forms

# Create your views here.

class BookListView (generic.ListView):
    template_name = "book_list.html"
    model = models.Books
    paginate_by = 10

class BookView (generic.DetailView):
    template_name = "view_book.html"
    model = models.Books

class BookCreateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.CreateView):
    model = models.Books
    form_class = forms.BookModelForm
    template_name = "add.html"
    login_url = reverse_lazy("staff:login")
    context_object_name = 'book_create'
    success_url = reverse_lazy('Home Page')
    success_message = 'Книга была успешно создана!'
    permission_required = "books.add_books"
     
    def get_success_url(self) -> str:
        self.object.picture_resizer()
        return super().get_success_url()


class BookUpdateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Books
    form_class = forms.BookModelForm
    template_name = "update.html"
    login_url = reverse_lazy("staff:login")
    context_object_name = 'book_update'
    success_url = reverse_lazy('Home Page')
    success_message = 'Книга была успешно обновлена!'
    permission_required = "books.change_books"

    def get_success_url(self) -> str:
        self.object.picture_resizer()
        return super().get_success_url()
   
class BookDeleteView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.DeleteView, ):
    model = models.Books
    template_name = "delete_book.html"
    login_url = reverse_lazy("staff:login")
    context_object_name = 'book_delete'
    success_url = reverse_lazy('Home Page')
    success_message = 'Книга была успешно удалена!'
    permission_required = "books.delete_books"

@login_required(login_url='staff:login')
def add_comment(request, comment_id):
    form = CommentForm()
    books = get_object_or_404(Books, pk=comment_id)
    user = request.user

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = user
            comment.book = books
            comment.save()
            return redirect('books:book_view', books.pk)

    context = {'form': form}

    return render(request, 'comment_form.html', context)

src/books/templates/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Add object {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token $%}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Add</button>
</form>

{% endblock BODY %}

src/books/templates/book_list.html
{% extends 'base.html' %}

{% block TITLE %}Books list{% endblock TITLE %}

{% block BODY %}

{% load user_tags1 %}

<div class="container text-center">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-9">
        
<table class="table table-bordered">
     <tr>
        <th>ID</th>
        <th>Название книги</th>
        <th>Изображение</th>
        <th>Цена</th>
        <th>Автор</th>
        <th>Серия</th>
        <th>Жанр</th>
        <th>Действия</th>
    </tr>
     {% for obj in object_list %}
    <tr>
        <td> {{ obj.pk }} </td>
        <td> {{ obj.book_name}} </td>
        <td>  <img src="{{ obj.book_picture_small }}" width="40" alt="...">  </td>
        <td> {{ obj.book_price}} BYN </td>
        <td> {{ obj.book_author}} </td>
        <td> {{ obj.book_serie}} </td>
        <td> {{ obj.book_genre}} </td>
        <td> 
            {% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%}  
            <a href = "{% url 'books:book_update' pk=obj.pk %}"><i class="bi bi-pencil-fill"></i></a>
            <a href = "{% url 'books:book_delete' pk=obj.pk %}"><i class="bi bi-trash3"></i></a>
            {% endif %}
            <a href = "{% url 'books:book_view' pk=obj.pk %}"><i class="bi bi-eye"></i></a>
        </td>
     </tr>
    {% endfor %}
</table>
{% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%}  
<a class="btn btn-primary" href="/books/book_add/" role="button">Add New</a>
{% endif %}
<br>
<br>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
    
         <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
    
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>



        </div>
        <div class="col">
        </div>
    </div>
</div>

{% endblock BODY %}

src/books/templates/comment_form.html
{% extends 'base.html' %}

{% block title %} Add a comment {% endblock %}

{% block BODY %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add this comment</button>
    </form>

{% endblock BODY %}

src/books/templates/delete_book.html
{% extends 'base.html' %}

{% block TITLE %} Delete book {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<b> Delete book {{ object.book_name }}? </b>
<form action="" method="post">
    {% csrf_token $%}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger" >Delete</button>
</form>

{% endblock BODY %}

src/books/templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Update {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token $%}
    {{ form|crispy }}
    <button type="submit" class="btn btn-info">Update</button>
</form>

{% endblock BODY %}

src/books/templates/view_book.html
{% extends 'base.html' %}

{% block TITLE %} Book view {% endblock TITLE %}

{% block BODY %}

        <!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src= {{ object.picture.url }} alt="..." /></div>
                    <div class="col-md-6">
                        <div class="small mb-1">ISBN {{object.book_isbn}}</div>
                        <h1 class="display-5 fw-bolder">{{object.book_name}}</h1>
                        <div class="fs-5 mb-5">
                          {% if object.is_active == "Y" %}
                            <span>{{object.book_price}} BYN</span>
                          {% else %} 
                            <span class="text-decoration-line-through">{{object.book_price}} BYN</span><br>
                            <button class="btn btn-danger" type="button" >
                              <i class="bi-cart-fill me-1"></i>
                              Нет в наличии
                          </button>
                          {% endif %}
                        </div>
                        <p class="lead">
                             <p>
                            Автор: {{ object.book_author }}
                            </p>  
                             <p>
                            Серия: {{object.book_serie}}
                            </p>
                            <p>      
                            Жанр: {{ object.book_genre }}  
                            </p>
                            <p>
                            <p class="p_rating">
                            Рейтинг: {{object.book_rating}} <span style="color:gold;">★</span>
                            </p>
                            Год издательства: {{object.book_year}}
                            </p>
                            <p>
                            Страницы: {{object.book_page}}
                            </p>
                            <p>
                            Переплёт: {{object.book_cover}}
                            </p>
                            <p>
                            Формат книги: {{object.format_book}}
                            </p>

                            <p>
                            Вес: {{object.book_weight}} г.
                            </p>
                            <p>
                            Ограничения по возрасту: {{object.book_age}}
                            </p>
                            <p>
                            Издательство: {{object.book_publisher}}
                            </p>
                            <p>
                            В наличии книг: {{object.book_quantity}}
                            </p>
                        </p>
                        {% if object.is_active == "Y" %}
                        <div class="d-flex">
                            <input class="form-control text-center me-3" id="add-to-cart" type="number" value="1" style="max-width: 3rem" />
                            <button class="btn btn-outline-dark flex-shrink-0" type="button" onclick="addToCart()">
                                <i class="bi-cart-fill me-1"></i>
                                Add to cart
                            </button>
                        {% else %} 
  
                        {% endif %}
                            
                    


                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="container text-center">

          <h2>Comments</h2>
      
        </div>
        <div class="card-text">
          
          {% if not books.comments.all %}
              <p>No comments yet ! <a class="text-primary" href="{% url 'books:add_comment' books.id %}">Add comment...</a></p>
      
          {% else %}
              <a class="text-primary" href="{% url 'books:add_comment' books.id %}">Add comment !</a><br/><br/>
              {% for comment in books.comments.all%}
                  <b>{{ comment.user }}</b> - <span class="text-muted" style="font-size: 13px;">{{ comment.date }}</span>
                  <p>{{ comment.body }}</p>
              {% endfor %}
      
          {% endif %}
        <!-- Footer-->
        <footer class="py-2 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Bookshop 2023 </p></div>
        </footer>


<script>
  
  function addToCart() {
    console.log("click")
    quantity = document.getElementById("add-to-cart")
    console.log(quantity.value)
    window.location.href = "{% url "orders:view-cart" %}" + "?good_id={{object.pk}}&quantity=" + quantity.value;
    
  }
</script>  

{% endblock BODY %}