src/directories/urls.py
from django.urls import path
from . import views
app_name = 'directories'

urlpatterns = [
    # path('success/', views.success_page, name="Success_Page"),
    path('authors_list_view/', views.AuthorListView.as_view(), name="authors_list"),
    path('genres_list_view/', views.GenreListView.as_view(), name= "genres_list"),
    path('publishers_list_view/', views.PublisherListView.as_view(), name="publishers_list"),
    path('series_list_view/', views.SerieListView.as_view(), name="series_list"),
    #Read
    path('author_view/<int:pk>', views.AuthorView.as_view(), name="author_view"),
    path('serie_view/<int:pk>', views.SerieView.as_view(), name="serie_view"),
    path('genre_view/<int:pk>', views.GenreView.as_view(), name="genre_view"),
    path('publisher_view/<int:pk>', views.PublisherView.as_view(), name="publisher_view"),
    #Delete
    path('author_delete/<int:pk>', views.AuthorDeleteView.as_view(), name="author_delete"),
    path('serie_delete/<int:pk>', views.SerieDeleteView.as_view(), name="serie_delete"),
    path('genre_delete/<int:pk>', views.GenreDeleteView.as_view(), name="genre_delete"),
    path('publisher_delete/<int:pk>', views.PublisherDeleteView.as_view(), name="publisher_delete"),
    #Create
    path('author_add/', views.AuthorCreateView.as_view(), name="author_add"),
    path('serie_add/', views.SerieCreateView.as_view(), name="serie_add"),
    path('genre_add/', views.GenreCreateView.as_view(), name="genre_add"),
    path('publisher_add/', views.PublisherCreateView.as_view(), name="publisher_add"),
    #Update
    path('author_upd/<int:pk>', views.AuthorUpdateView.as_view(), name="author_update"),
    path('serie_upd/<int:pk>', views.SerieUpdateView.as_view(), name="serie_update"),
    path('genre_upd/<int:pk>', views.GenreUpdateView.as_view(), name="genre_update"),
    path('publisher_upd/<int:pk>', views.PublisherUpdateView.as_view(), name="publisher_update"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views


urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace ='directories'), name = "directories"),
    path('staff/', include('staff.urls', namespace ='staff'), name = "staff"),
    path('orders/', include('orders.urls', namespace ='orders'), name = "orders"),
    path('books/', include('books.urls', namespace ='books'), name = "books"),
    path('search/', include('search.urls', namespace ='search'), name = "search"),
    path('', home_views.HomePage.as_view(), name="Home Page"),
  
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/directories/models.py
from pathlib import Path
from django.db import models
from django.urls import reverse_lazy
from PIL import Image

# Create your models here.

class Author(models.Model): 
    picture = models.ImageField(
            verbose_name="Author picture",
            upload_to="uploads/%Y/%m/%d/"
    )
    author_firstname = models.CharField(
            verbose_name = 'Author Name',
            max_length = 15,
            null = False,
            blank = False,
            default = "Author's firstname",
            help_text= "Add Author's name, max len = 15"
    )
    author_lastname = models.CharField(
            verbose_name = 'Author Lastname',
            max_length=15,
            null = False,
            blank = False,
            default = "Author's lastname",
            help_text= "Add Author's lastname, max len = 15"
    )
    author_bio = models.TextField(
            verbose_name = 'Author Bio',
            null = True,
            blank = True,
            help_text= "Author's biography, max len = 1000"
    )
    def __str__(self):
        return str(self.author_lastname)+ " " + str(self.author_firstname)
 
    def get_absolute_url(self):
        return reverse_lazy ('Home Page')

    def get_search_url_author(self):
        return f"/directories/author_view/{self.pk}"

    def author_picture_med (self):
        original_url = self.picture.url
        new_url = original_url.split('.')
        picture_url = ".".join(new_url[:-1]) + "_150_." + new_url[-1]
        return picture_url

    def author_picture_small (self):
        original_url = self.picture.url
        new_url = original_url.split('.')
        picture_url = ".".join(new_url[:-1]) + "_40_." + new_url[-1]
        return picture_url

    def picture_resizer (self):
        extention = self.picture.file.name.split('.')[-1]
        BASE_DIR = Path(self.picture.file.name).resolve().parent
        file_name = Path(self.picture.file.name).resolve().name.split('.')
        for m_basewidth in [150, 40]:
                im = Image.open(self.picture.file.name)
                wpercent = (m_basewidth/float(im.size[0]))
                hsize = int((float(im.size[1])*float(wpercent)))
                im.thumbnail ((m_basewidth ,hsize), Image.Resampling.LANCZOS)
                im.save(str(BASE_DIR / '.'.join(file_name[:-1])) + f'_{m_basewidth}_.' + extention)
    
class Serie(models.Model):
    picture = models.ImageField(
            verbose_name="Serie picture",
            upload_to="uploads/%Y/%m/%d/"
    )
    serie_name = models.CharField(
            verbose_name = 'Serie',
            max_length = 40,
            null = False,
            blank = False,
            default = "Serie name"
    )
    serie_description = models.TextField(
            verbose_name ='Serie description',
            null = True,
            blank = True  
    )  
    def __str__(self):
        return (self.serie_name)

    def get_absolute_url(self):
        return reverse_lazy ('directories:Success_Page')
    
    def get_search_url_serie(self):
        return f"/directories/serie_view/{self.pk}"
    
class Genre(models.Model):
    genre_name = models.CharField(
            verbose_name = 'Genre',
            max_length = 30,
            null = False,
            blank = False,
            default="Genre name"
    )
    genre_description = models.TextField(
            verbose_name = 'Genre description',
            null = True,
            blank = True
    )
    picture = models.ImageField(
        verbose_name="Genre picture",
        upload_to="uploads/%Y/%m/%d/"
    )
    def __str__(self):
        return (self.genre_name)

    def get_absolute_url(self):
        return reverse_lazy ('directories:Success_Page')

    def get_search_url_genre(self):
        return f"/directories/genre_view/{self.pk}"
    
class Publisher(models.Model):
    picture = models.ImageField(
        verbose_name="Publisher picture",
        upload_to="uploads/%Y/%m/%d/"
    )
    
    publisher_name = models.CharField(
            verbose_name = 'Publisher',
            max_length = 30,
            null = False,
            blank = False,
            default = "Publisher's name"
    )
    publisher_description = models.TextField(
            verbose_name = 'Publisher description',
            null=True,
            blank=True
    )
    def __str__(self):
        return (self.publisher_name)

    def get_absolute_url(self):
        return reverse_lazy ('directories:Success_Page')
    
    def get_search_url_publisher(self):
        return f"/directories/publisher_view/{self.pk}"

src/directories/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class AddAuthorForm(forms.Form):
    author_firstname = forms.CharField(
        required = True,
        label= "Pls select an author firstname",
        help_text="this is a test helptext"
    )
    author_lastname = forms.CharField( 
        max_length=50, 
        required=True,
        label="pls add an author lastname"
    )
    author_bio = forms.CharField( 
        max_length=50, 
        required=True,
        label="pls add an author biography"
    )
    def save (self):
        models.Author.objects.create()

class AuthorModelForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = (
            'picture',
            'author_firstname', 
            'author_lastname',
            'author_bio'
        )
        

src/directories/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from . import models
from . import forms

#Author

class AuthorListView (generic.ListView):
    template_name = "author_list.html"
    model = models.Author
    paginate_by = 10

class AuthorView (generic.DetailView):
    template_name = "view_authors.html"
    model = models.Author

class AuthorCreateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.CreateView,):
    model = models.Author
    form_class = forms.AuthorModelForm
    template_name = "add.html"
    login_url = reverse_lazy("staff:login")
    context_object_name = 'author_create'
    success_url = reverse_lazy('Home Page')
    success_message = 'Автор был успешно создан!'
    permission_required = "directories.author_create"

    
    def get_success_url(self) -> str:
        self.object.picture_resizer()
        return super().get_success_url()
    
class AuthorUpdateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Author
    form_class = forms.AuthorModelForm
    template_name = "update.html"
    login_url = reverse_lazy("staff:login")
    success_url = reverse_lazy('Home Page')
    context_object_name = 'author_update'
    success_message = 'Автор был успешно обновлен'
    permission_required = ('directories.change_author')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Автор обновлен'
        return context

class AuthorDeleteView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Author
    template_name = "delete_author.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'author_delete'
    success_message = "Автор был успешно удален!"
    permission_required = ('directories.delete_author')
    
# Serie

class SerieListView (generic.ListView):
    template_name = "series_list.html"
    model = models.Serie
    paginate_by = 10

class SerieView (generic.DetailView):
    template_name = "view_series.html"
    model = models.Serie

class SerieCreateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.CreateView):
    model = models.Serie
    fields = [
        'serie_name', 'serie_description', 'picture'
    ]
    template_name = "add.html"
    success_url = reverse_lazy('directories:series_list')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'serie_create'
    success_message = "Серия успешно создана!"
    permission_required = ('directories.add_serie')
    
class SerieUpdateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Serie
    fields = [
        'serie_name', 'serie_description', 'picture'
    ]
    template_name = "update.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'serie_update'
    success_message = "Серия была успешно обновлена!"
    permission_required = ('directories.change_serie')
 
class SerieDeleteView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Serie
    template_name = "delete_series.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'serie_delete'
    success_message = "Серия была успешно удалена!"
    permission_required = ('directories.delete_serie')
     
# Genres

class GenreListView (generic.ListView):
    template_name = "genres_list.html"
    model = models.Genre
    paginate_by = 10
    

class GenreView (generic.DetailView):
    template_name = "view_genres.html"
    model = models.Genre

class GenreCreateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.CreateView):
    model = models.Genre
    fields = [
        'genre_name', 'genre_description', 'picture'
    ]
    template_name = "add.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'genre_create'
    success_message = "Серия была успешно создана!"
    permission_required = ('directories.add_genre')
    
class GenreUpdateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Genre
    fields = [
        'genre_name', 'genre_description', 'picture'
    ]
    template_name = "update.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'genre_update'
    success_message = "Жанр был успешно обновлен!"
    permission_required = ('directories.change_genre')
  
class GenreDeleteView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Serie
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'genre_delete'
    success_message = "Жанр был успешно удален!"
    permission_required = ('directories.delete_genre')
    
#Publishers 

class PublisherListView (generic.ListView):
    template_name = "publishers_list.html"
    model = models.Publisher
    paginate_by = 10

class PublisherView (generic.DetailView):
    template_name = "view_publishers.html"
    model = models.Publisher

class PublisherCreateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.CreateView):
    model = models.Publisher
    fields = [
        'publisher_name', 'publisher_description', 'picture'
    ]
    template_name = "add.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'publisher_create'
    success_message = "Издатель был успешно создан!"
    permission_required = ('directories.add_publisher')
    
class PublisherUpdateView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.UpdateView):
    model = models.Publisher
    fields = [
        'publisher_name', 'publisher_description', 'picture'
    ]
    template_name = "update.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'publisher_update'
    success_message = "Издатель был успешно обновлен!"
    permission_required = ('directories.change_publisher')
 
    
class PublisherDeleteView (LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, generic.DeleteView):
    model = models.Publisher
    template_name = "delete_publishers.html"
    success_url = reverse_lazy('Home Page')
    login_url = reverse_lazy("staff:login")
    context_object_name = 'publisher_delete'
    success_message = "Издатель был успешно удален!"
    permission_required = ('directories.delete_publisher')
  
     

src/directories/templates/add_author.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Add author {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token $%}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Add</button>
</form>

{% endblock BODY %}

src/directories/templates/author_list.html
{% extends 'base.html' %}

{% block TITLE %}Authors list{% endblock TITLE %}

{% block BODY %}

{% load user_tags %}

<div class="container text-center">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-6">
        
<table class="table table-bordered">
     <tr>
        <th>pk</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>actions</th>
    </tr>
     {% for obj in object_list %}
    <tr>
        <td> {{ obj.pk }} </td>
        <td> {{ obj.author_firstname }} </td>
        <td> {{ obj.author_lastname }} </td>
        <td> 
             
            {% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%}  
            <a href = "{% url 'directories:author_update' pk=obj.pk %}"><i class="bi bi-pencil-fill"></i></a>
            <a href = "{% url 'directories:author_delete' pk=obj.pk %}"><i class="bi bi-trash3"></i></a>
            {% endif %}
            <a href = "{% url 'directories:author_view' pk=obj.pk %}"><i class="bi bi-eye"></i></a>
            
        </td>
     </tr>
    {% endfor %}
</table>

{% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%}  
<a class="btn btn-primary" href="/directories/author_add/" role="button">Add New</a>
{% endif %}

<br>
<br>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
    
         <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
    
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>



        </div>
        <div class="col">
        </div>
    </div>
</div>

{% endblock BODY %}

src/directories/templates/delete_genres.html
{% extends 'base.html' %}

{% block TITLE %} Delete genre {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<h1>Genre # {{ object.pk }}</h1>
<b> Genre's name </b> {{ object.genre_name }}
<form action="" method="post">
    {% csrf_token $%}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger" >Delete</button>
</form>

{% endblock BODY %}

src/directories/templates/delete_publishers.html
{% extends 'base.html' %}

{% block TITLE %} Delete publisher {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<h1>Publisher # {{ object.pk }}</h1>
<b> Publisher's name </b> {{ object.publisher_name }}
<form action="" method="post">
    {% csrf_token $%}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

{% endblock BODY %}  

src/directories/templates/delete_series.html
{% extends 'base.html' %}

{% block TITLE %} Delete serie {% endblock TITLE %}

{% block BODY %}

<h1> {{ greeting }} </h1>
<h1>Serie # {{ object.pk }}</h1>
<b> Serie name </b> {{ object.serie_name }}
<br>
<b> Serie description </b> {{ object.serie_description }}
<form action="" method="post">
    {% csrf_token $%}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

{% endblock BODY %}  

src/directories/templates/genres_list.html
{% extends 'base.html' %}

{% block TITLE %} Genres list {% endblock TITLE %}

{% block BODY %}

{% load user_tags %}

<div class="container text-center">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-6">

<table class="table table-bordered">
    <tr>
        <th>pk</th>
        <th>Genre name</th>
        <th>Genre descripton</th>
        <th>Actions</th>
    </tr>
    {% for obj in object_list %}
    <tr>
        <td> {{ obj.pk }} </td>
        <td> {{ obj.genre_name }} </td>
        <td> {{ obj.genre_description }} </td>
        <td>
            {% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%}  
            <a href = "{% url 'directories:genre_update' pk=obj.pk %}"><i class="bi bi-pencil-fill"></i></a>
            <a href = "{% url 'directories:genre_delete' pk=obj.pk %}"><i class="bi bi-trash3"></i></a>
            {% endif %}
            <a href = "{% url 'directories:genre_view' pk=obj.pk %}"><i class="bi bi-eye"></i></a>
        </td>
    </tr>
    {% endfor %}
</table>
            {% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%} 
            <a class="btn btn-primary" href="/directories/genre_add/" role="button">Add New</a>
            {% endif %}
<br>
<br>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


        </div>
        <div class="col">
        </div>
    </div>
</div>

{% endblock BODY %}

src/directories/templates/series_list.html
{% extends 'base.html' %}

{% block TITLE %}Series list{% endblock TITLE %}

{% block BODY %}

{% load user_tags %}

<div class="container text-center">
    <div class="row">
        <div class="col">
        </div>
        <div class="col-8">

<table class="table table-bordered">
    <tr>
        <th>pk</th>
        <th>Serie name</th>
        <th>Serie descripton</th>
        <th>Actions</th>
    </tr>
    {% for obj in object_list %}
    <tr>
        <td> {{ obj.pk }} </td>
        <td> {{ obj.serie_name }} </td>
        <td> {{ obj.serie_description }} </td>
        <td> 
            {% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%} 
            <a href = "{% url 'directories:serie_update' pk=obj.pk %}"><i class="bi bi-pencil-fill"></i></a>
            <a href = "{% url 'directories:serie_delete' pk=obj.pk %}"><i class="bi bi-trash3"></i></a>
            {% endif %}
            <a href = "{% url 'directories:serie_view' pk=obj.pk %}"><i class="bi bi-eye"></i></a>
        </td>
    </tr>
    {% endfor %}
</table>
{% if request.user|has_group:"Managers" %} {% elif request.user|has_group:"Admins"%} 
<a class="btn btn-primary" href="/directories/serie_add/" role="button">Add New</a>
{% endif %}

<br>
<br>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

        </div>
        <div class="col">
        </div>
    </div>
</div>

{% endblock BODY %}

src/directories/templates/success_page.html
{% extends 'base.html' %}

{% block TITLE %} Success page {% endblock TITLE %}

{% block BODY %}

<h1> {{ message }} </h1>

{% endblock BODY %}

src/directories/templates/view_authors.html
{% extends 'base.html' %}

{% block TITLE %} Author view {% endblock TITLE %}

{% block BODY %}


    <section class="py-5">
      <div class="container px-4 px-lg-5 my-5">
          <div class="row gx-4 gx-lg-5 align-items-center">
              <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src={{ object.picture.url }} alt="..." /></div>
              <div class="col-md-6">
                  <h1 class="display-5 fw-bolder">{{ object.author_firstname }} {{ object.author_lastname }}</h1>
                  <p class="lead">{{ object.author_bio }}</p>
              </div>
          </div>
      </div>
  </section>



    <!-- Footer-->
    <footer class="py-2 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Bookshop 2023 </p></div>
    </footer>



{% endblock BODY %}

src/directories/templates/view_genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Genres</title>
</head>
<body>
    <h1>Genre # {{ object.pk }}</h1>
    <b> Genre's name </b> {{ object.genre_name }}
</body>
</html>

src/directories/templates/view_genres.html
{% extends 'base.html' %}

{% block TITLE %} Genres view {% endblock TITLE %}

{% block BODY %}



    <section class="py-5">
      <div class="container px-4 px-lg-5 my-5">
          <div class="row gx-4 gx-lg-5 align-items-center">
              <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src={{ object.picture.url }} alt="..." /></div>
              <div class="col-md-6">
                  <h1 class="display-5 fw-bolder">{{ object.genre_name }} </h1>
                  <p class="lead">{{ object.genre_description }}</p>
              </div>
          </div>
      </div>
  </section>



    <!-- Footer-->
    <footer class="py-2 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Bookshop 2023 </p></div>
    </footer>



{% endblock BODY %}

src/directories/templates/view_publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publishers</title>
</head>
<body>
    <h1>Publisher # {{ object.pk }}</h1>
    <b> Publisher's name </b> {{ object.publisher_name }}
</body>
</html>

src/directories/templates/view_publishers.html
{% extends 'base.html' %}

{% block TITLE %} Genres view {% endblock TITLE %}

{% block BODY %}



    <section class="py-5">
      <div class="container px-4 px-lg-5 my-5">
          <div class="row gx-4 gx-lg-5 align-items-center">
              <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src={{ object.picture.url }} alt="..." /></div>
              <div class="col-md-6">
                  <h1 class="display-5 fw-bolder">{{ object.publisher_name }} </h1>
                  <p class="lead">{{ object.publisher_description }}</p>
              </div>
          </div>
      </div>
  </section>



    <!-- Footer-->
    <footer class="py-2 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Bookshop 2023 </p></div>
    </footer>



{% endblock BODY %}

src/directories/templates/view_series.html
{% extends 'base.html' %}

{% block TITLE %} Genres view {% endblock TITLE %}

{% block BODY %}



    <section class="py-5">
      <div class="container px-4 px-lg-5 my-5">
          <div class="row gx-4 gx-lg-5 align-items-center">
              <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src={{ object.picture.url }} alt="..." /></div>
              <div class="col-md-6">
                  <h1 class="display-5 fw-bolder">{{ object.serie_name }} </h1>
                  <p class="lead">{{ object.serie_description }}</p>
              </div>
          </div>
      </div>
  </section>



    <!-- Footer-->
    <footer class="py-2 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Bookshop 2023 </p></div>
    </footer>



{% endblock BODY %}