src/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartDetailView.as_view(), name="view-cart"),
    path('cart-items-edit/', views.CartAddDeleteItemView.as_view(), name="cart-items-edit"),
    path('create-order/', views.CreateOrder.as_view(), name="create-order"),
    path('complete-order/', views.OrderSuccess.as_view(), name="complete-order"),
    path('orders-history/', views.history_order, name="history-order"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views


urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace ='directories'), name = "directories"),
    path('staff/', include('staff.urls', namespace ='staff'), name = "staff"),
    path('orders/', include('orders.urls', namespace ='orders'), name = "orders"),
    path('books/', include('books.urls', namespace ='books'), name = "books"),
    path('search/', include('search.urls', namespace ='search'), name = "search"),
    path('', home_views.HomePage.as_view(), name="Home Page"),
  
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from books.models import Books
from django.shortcuts import render

# Create your models here.

User = get_user_model()

class Cart (models.Model):
    customer = models.ForeignKey(
        User,
        verbose_name = "customer",
        on_delete = models.PROTECT,
        related_name = "carts",
        null = True,
        blank= True
    )
    @property
    def total_price(self):
        total_price = 0
        for good_in_cart in self.goods.all():
            total_price += good_in_cart.price
        return total_price
    
    @property
    def total_quantity(self):
        total_quantity = 0
        for good_in_cart in self.goods.all():
            total_quantity += good_in_cart.quantity
        return total_quantity
    

class GoodInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        verbose_name='Cart',
        on_delete=models.CASCADE,
        related_name='goods'
    )   
    
    good = models.ForeignKey(
        Books,
        verbose_name= "Book",
        on_delete = models.PROTECT
    )
    
    quantity = models.PositiveIntegerField(
        verbose_name='quantity',
        default=1
    )
    
    price = models.DecimalField(
        verbose_name= 'Price',
        max_digits=6,
        decimal_places=2
    )
    created = models.DateTimeField(
        verbose_name='created',
        auto_now_add=True,
        auto_now=False
    )
    updated = models.DateTimeField(
        verbose_name='updated',
        auto_now_add=False,
        auto_now=True
    )
    def __str__(self) -> str:
        return f"{self.good.book_name} x {self.quantity}"
        

class Order (models.Model):
    delivery_address = models.TextField(
        verbose_name = "Delivery address",
        default = "Enter your adress"
    )

    phone = models.CharField(
        verbose_name = "Phone",
        default = "Enter your Phone",
        max_length=10
    ) 

    STATUSES = (
        ('Новый', "NEW"),
        ('Оформлен', "OFORMLEN"),
        ('В работе', "ATWORK"),
        ('Выдан', "VYDAN"),
        ('Отеменен', "CLOSED")
    )
    status = models.CharField(
        max_length=8,
        choices= STATUSES,
        default='NEW'
    )
    cart = models.OneToOneField(
        Cart,
        verbose_name="Cart",
        on_delete=models.PROTECT
    )
    created = models.DateTimeField(
        verbose_name='created',
        auto_now_add=True,
        auto_now=False
    )
    updated = models.DateTimeField(
        verbose_name='updated',
        auto_now_add=False,
        auto_now=True        
    )

src/orders/forms.py
from django import forms
from .models import Order

class CreateOrderForm(forms.Form):
    delivery_address = forms.CharField(
        required=True, 
        widget=forms.Textarea
    )
    phone = forms.CharField(
        required=True
    )
    

src/orders/views.py
from typing import Any, Dict, Optional
from django.db import models
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, FormView, TemplateView, UpdateView
from books.models import Books
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from . import models, forms
from .models import Cart, Order, GoodInCart

# Create your views here.

class CartDetailView(DetailView):
    template_name = "orders/cart.html"
    model = models.Cart
    
    def get_object (self, *args, **kwargs):
        cart_pk = self.request.session.get("cart_id")
        customer = self.request.user
        if customer.is_anonymous:
            customer = None
        cart, created = models.Cart.objects.get_or_create(
            pk = cart_pk,
            defaults={
                "customer":customer
            }           
        )
        if not cart_pk:
            self.request.session['cart_id'] = cart.pk
        good_id = self.request.GET.get("good_id")
        print (good_id)
        quantity= self.request.GET.get("quantity")
        print (quantity)
        if good_id and quantity:
            quantity = int(quantity)
            good = Books.objects.get (pk=int(good_id))
            price = good.book_price
            good_in_cart, good_in_cart_created = models.GoodInCart.objects.get_or_create(
                cart = cart,
                good = good,
                defaults= {
                    "quantity":quantity,
                    "price":price * quantity
                }
            )
            if not good_in_cart_created:
                good_in_cart.quantity = good_in_cart.quantity + quantity
                good_in_cart.price = good_in_cart.price + price*quantity
                good_in_cart.save() 
        return cart 
    
class CartAddDeleteItemView(DetailView):
    template_name = "orders/cart.html"
    model = models.Cart
    
    def get_object (self, *args, **kwargs):
        cart_pk = self.request.session.get("cart_id")
        customer = self.request.user
        if customer.is_anonymous:
            customer = None
        cart, created = models.Cart.objects.get_or_create(
            pk = cart_pk,
            defaults={
                "customer":customer
            }           
        )
        if not cart_pk:
            self.request.session['cart_id'] = cart.pk
        good_id = self.request.GET.get("good")
        action= self.request.GET.get("action")
        if good_id and action and action in ['add', 'delete']:
            good = Books.objects.get (pk=int(good_id))
            price = good.book_price
            good_in_cart = get_object_or_404(
                models.GoodInCart, 
                cart__pk = cart.pk,
                good__pk = good.pk,
            )
            if action == "add":
                addiction = 1
            else:
                if good_in_cart.quantity <= 1:
                    good_in_cart.delete()
                    return cart
                addiction = -1
            good_in_cart.quantity = good_in_cart.quantity + addiction
            good_in_cart.price = good_in_cart.quantity * price
            good_in_cart.save()
            
        return cart 
    
class CreateOrder (SuccessMessageMixin, FormView):    
    form_class = forms.CreateOrderForm
    template_name = "orders/create_order.html"
    success_url = reverse_lazy("Home Page")
    success_message = "Заказ был успешно оформлен!"
    
    def form_valid(self, form):
        delivery_address = form.cleaned_data.get("delivery_address")
        phone = form.cleaned_data.get("phone")
        status = "Новый"
        cart_pk = int(self.request.session.get("cart_id"))
        cart = get_object_or_404(
            models.Cart,
            pk=cart_pk
        )
        obj = models.Order.objects.create(
            delivery_address = delivery_address,
            phone = phone,
            status = status,
            cart = cart
        )
        del self.request.session["cart_id"]
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", -100)
        
        context['object'] = get_object_or_404(
            models.Cart,
            pk=int(cart_id)
        )
        return context

class OrderUpdateView(UpdateView):
    model= Order
    form_class= forms.CreateOrderForm
    template_name = "orders/order_update.html"
    success_url= 'order-complete'


class OrderSuccess(TemplateView):
    template_name = "orders/order-complete.html"
    
def history_order(request):
    context={}
    user_id = None
    good = None
    if request.user.is_authenticated:
        user_id = request.user
    carts = Cart.objects.filter(customer=user_id)
    orders = Order.objects.filter(cart_id__in=carts)
    context = {
        'user_carts': carts,
        'user_orders': orders,
    }
    print("context : ", context)
    return render(request, template_name="orders/history_order.html", context=context)

src/orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Корзина {% endblock TITLE %}

{% block BODY %}

<h1>Корзина</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Название</th>
        <th scope="col">Количество</th>
        <th scope="col">Редактировать</th>
        <th scope="col">Цена</th>
      </tr>
    </thead>
    <tbody>
         {% for good_in_cart in object.goods.all %}
      <tr>
        <th scope="row">{{ forloop.counter }} </th>
        <td>{{ good_in_cart.good}}</td>
        <td>{{ good_in_cart.quantity}}</td>
        <td>
            <button type="button" onclick="deleteGood({{ good_in_cart.good.pk }})" class="btn btn-outline-danger btn-sm">-</button> 
            <button type="button" onclick="addGood({{ good_in_cart.good.pk}})"class="btn btn-outline-primary btn-sm">+</button> 
        </td>
        <td>{{ good_in_cart.price}}</td>
      </tr>
      {% endfor %}
      <tr>
        <td colspan="2">Сумма:</td>
        <td colspan="2">{{object.total_quantity}}</td>
        <td>{{ object.total_price }}</td>
      </tr>
    </tbody>
  </table>
  {% if object.goods.all %} 
    <a href="{% url 'orders:create-order' %}" class="btn btn-outline-primary">Создать заказ</a>
  {% endif %}
  <script>
    function addGood(pk) {
        console.log("add " + pk)
        redirect("add", pk)
    }
    function deleteGood(pk) {
        console.log("delete " + pk)
        redirect("delete", pk)
    }
    function redirect(action, pk) {
        window.location.href = "{% url "orders:cart-items-edit" %}" + `?action=${action}&good=${pk}`;
    }
  </script>

{% endblock BODY %}

src/orders/templates/orders/create_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Cart {% endblock TITLE %}

{% block BODY %}

<h1>Cart</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">price</th>
      </tr>
    </thead>
    <tbody>
         {% for good_in_cart in object.goods.all %}
      <tr>
        <th scope="row">{{ forloop.counter }} </th>
        <td>{{ good_in_cart.good}}</td>
        <td>{{ good_in_cart.quantity}}</td>
        <td>{{ good_in_cart.price}}</td>
      </tr>
      {% endfor %}
      <tr>
        <td colspan="2">Total:</td>
        <td colspan>{{object.total_quantity}}</td>
        <td>{{ object.total_price }}</td>
      </tr>
    </tbody>
  </table> 

<form action="" method="post">
    {% csrf_token %}
    {{ form | crispy}}
    <button type = "submit" class="btn btn-danger">Create</button>
</form>


{% endblock BODY %}

src/orders/templates/orders/history_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Cart {% endblock TITLE %}

{% block BODY %}

<h1>История заказов</h1>


<table class="table table-bordered">
        <tr>
           <th>Номер заказа</th>
           <th>Статус</th>
           <th>Дата создания</th>

        </tr>
       {% for order in user_orders %}
       <tr>
           <td> {{ order.pk }} </td>
           <td> {{ order.status }} </td>
           <td> {{ order.created }} </td>
        </tr>
       {% endfor %}
   </table>


{% endblock BODY %}

src/orders/templates/orders/order-complete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block TITLE %} Cart {% endblock TITLE %}

{% block BODY %}

<h1>Order complete!</h1>




{% endblock BODY %}